### ISSUE TITLE
Bokeh vs. Hoviews

### ISSUE THREAD

**Issue by thequackdaddy** [jbogaardt/chainladder-python#13]
So I agree that Bokeh is very pretty. But my experiments with it have left me a little bit overwhelmed with the complexity and large amounts of code necessary to get really pretty graphs. 

Well, holoviews to the rescue. Holvoiews is essentially a wrapper for Bokeh (and matplotlib for that matter) so that you lose a little bit of the flexibility, but writing graphs is much, much easier (IMHO).

**Comment by jbogaardt** [comment]
@thequackdaddy,  I've never heard of Holoviews, but I'm all for making code simpler.  I'll read up on it.

**Comment by jbogaardt** [comment]
The `Triangle` API from which most plotting would occur is now very closely coupled with pandas, I'm beginning to form the opinion that plotting should be decided by the user and not by this package.  It also helps in keeping the scope of the package narrower.  With close coupling to `pandas.DataFrame`, the `plot()` method feels the more natural fit, and that is available.  Beyond that, the fragmented python viz landscape is keeping me on the sidelines.  If you disagree, let me know.  Otherwise, I'll close close this as now out of scope.
