### ISSUE TITLE
Load datasets fails 

### ISSUE THREAD

**Issue by johalnes** [jbogaardt/chainladder-python#21]
Tried some of the examples listed in the 2.0.1 documentation. 

In the pd.read_pickle() function the input name is converted to lower keys, but when installed from PIP many of the datasets is named with uppercase 
![skjermbilde 2019-01-25 kl 22 20 10](https://user-images.githubusercontent.com/8577145/51773608-a6d8a800-20ef-11e9-8a11-20a19e064ca9.png)
 which gives error on many of the nice examples provided on read the docs. 

Using read_pickle direct on path where package is installed works.

**Comment by jbogaardt** [comment]
This is interesting.  I did convert the file names to all lower case in the >=0.2.0 versions because of ambiguity of case sensitivity on windows vs linux.  I'm wondering if you had an older version of `chainladder` in your pip cache that kept the old files.
Maybe uninstalling and reinstalling using:
`pip install chainladder --no-cache-dir` might resolve the issue.  Let me know.

**Comment by jbogaardt** [comment]
I think I figured it out.  The distribution on [Pypi](https://pypi.org/project/chainladder/) had reference to the old pickles despite the changes on github.  Github itself by default seems to ignore case changes in file names.

I believe it works on mac and windows since the file systems there do not care about case sensitivity.  In linux, as you've noted, it is a problem.  Rather than renaming the file, I recreated them using the lowercase names and the distribution seems to be catching the changes. I've put release **0.2.2** on Pypi, and hopefully this is all your docker image needs to find.  Keep me posted if you're still running into issues.

**Comment by johalnes** [comment]
Works like a charm! Nicely done!

May I ask if you have any plans of implementing the plot functions from 0.1.x version or is there too many possibilities now with the 4D data structure?

**Comment by jbogaardt** [comment]
Glad it worked. 

I haven't thought too hard about plotting in 0.2.x.  One thing I learned between 0.1.x and 0.2.0 is that writing a flexible API is really difficult (this is why I opted to 'steal' from pandas and scikit-learn with the latest releases).  A plotting API would be no different.

In my own usage though, I find that the `Triangle.to_frame()` method makes it trivial to get key info into a DataFrame, and from there you can plot with whatever plotting packages you want.  Almost everything returns a `Triangle` instance so almost everything is easily converted to a DataFrame.  You don't get canned pretty graphs, but I imagine any serious user would grow out of the canned exhibits quickly anyway.
