### ISSUE TITLE
Errors in projecting incomplete triangles

### ISSUE THREAD

**Issue by peterdavidsonONE** [jbogaardt/chainladder-python#50]
If you have multiple LOB in a triangle, but not all LOB have the same time period, then for some LOB the triangle fills the first rows and last columns with NaN and throws errors on computation.
e.g. a new LOB mixed with established LOB.
I got some div-by-zero errors and dimension errors when trying to apply the chainladder method.

**Comment by jbogaardt** [comment]
I am attempting to replicate your issue with sample data.  Let me know if this sample slice from the clrd dataset does not match your issue.
```python
import chainladder as cl
clrd = cl.load_dataset('clrd')['CumPaidLoss']
# Pick a complete and a partial triangle
clrd = clrd[clrd['LOB']=='wkcomp'].iloc[-6:-4]
model = cl.Chainladder().fit(clrd) # Throws warnings and doesn't work for partial triangle
```
This is a difficult one to solve in a general way.  The issue is that the LDFs want to be created for each development period in the overall triangle, but cannot do so when data does not exist for the new LOB.  

Having a single triangle object is nice for slicing and manipulating, but pushing jagged triangles through the model fits is troublesome (and currently unsupported).  An alternative, is to create a separate triangle for the new line and run that through as a stand-alone model:
```python
# Slice new LOB out
new_lob = clrd.iloc[-1]
# Limit shape to known data
new_lob = new_lob[new_lob.origin>='1996'][new_lob.development<=24]
# Fit Chainladder to new LOB
cl.Chainladder().fit(new_lob)
```

Give that a try, and let me know.

**Comment by peterdavidsonONE** [comment]
That does replicate the problem, as well as provide a workaround.
It is convenient to load the data into a single triangle, but then I think I need to write a 'shrink' method for a triangle, after it has been sliced, but before a method is fitted, to remove the blank rows/columns.
Otherwise, I think the usefulness of the triangle indexing is somewhat limited: for example data containing claims by lob and tariff information would come from a single data set. It is useful to look at developments at different granularity, as tariffs perhaps changing regularly.

**Comment by jbogaardt** [comment]
A `shrink` method would be useful or perhaps borrowing the `dropna()` method name to keep close to pandas notation.
